config/routes.rb
Rails.application.routes.draw do
  resources :todo_lists do
    resources :todo_items
  end
  root to: "todo_lists#index"

  # Sidekiq has a web dashboard which you can enable below. It's turned off by
  # default because you very likely wouldn't want this to be available to
  # everyone in production.
  #
  # Uncomment the 2 lines below to enable the dashboard WITHOUT authentication,
  # but be careful because even anonymous web visitors will be able to see it!
  # require "sidekiq/web"
  # mount Sidekiq::Web => "/sidekiq"
  #
  # If you add Devise to this project and happen to have an admin? attribute
  # on your user you can uncomment the 4 lines below to only allow access to
  # the dashboard if you're an admin. Feel free to adjust things as needed.
  # require "sidekiq/web"
  # authenticate :user, lambda { |u| u.admin? } do
  #   mount Sidekiq::Web => "/sidekiq"
  # end

  # Learn more about this file at: https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :todo_list

  validates :name, presence: true

  validates :due_date, comparison: { greater_than_or_equal_to: Date.today }, if: :due_date


  scope :completed, -> { where(completed: true) }
  scope :pending, -> { where(completed: false) }
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
  has_many :items, class_name: "TodoItem", dependent: :destroy

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  include Dry::Monads[:result]

  before_action :set_todo_list
  before_action :set_todo_item, only: %i[show edit update destroy]

  def index
    @todo_items = @todo_list.items.order(created_at: :desc)
  end

  def show
  end

  def new
    @todo_item = @todo_list.items.new
  end

  def edit
    render partial: "edit", locals: { todo_item: @todo_item }
  end

  def create
    @todo_item = @todo_list.items.new(todo_item_params)

    result = TodoItems::CreateTodoItemService.new(@todo_list, todo_item_params).call

    case result
    when Success
      @todo_item = result.success

      respond_to do |format|
        format.turbo_stream
      end
    when Failure
      respond_to do |format|
        format.turbo_stream { render turbo_stream: turbo_stream.update("new_todo_item", partial: "todo_items/form", locals: { todo_item: @todo_item, errors: result.failure }), status: :unprocessable_entity }
      end
    end
  end

  def update
    result = TodoItems::UpdateTodoItemService.new(@todo_item, todo_item_params).call

    case result
    when Success
      respond_to do |format|
        format.turbo_stream { }
        format.json { render :show, status: :ok, location: @todo_item }
      end
    when Failure
      respond_to do |format|
        format.turbo_stream { render turbo_stream: turbo_stream.update("edit_todo_item", partial: "todo_items/form", locals: { todo_item: @todo_item, errors: result.failure }), status: :unprocessable_entity }
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    result = TodoItems::DestroyTodoItemService.new(@todo_item).call

    case result
    when Success
      respond_to do |format|
        format.turbo_stream { }
        format.json { head :no_content }
      end
    when Failure
      respond_to do |format|
        format.turbo_stream { render turbo_stream: turbo_stream.replace("todo_item_#{@todo_item.id}", partial: "todo_items/todo_item", locals: { todo_item: @todo_item, errors: result.failure }), status: :unprocessable_entity }
        format.html { render :index, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_todo_list
    @todo_list = TodoList.find(params[:todo_list_id])
  end

  def set_todo_item
    @todo_item = TodoItem.find(params[:id])
  end

  def todo_item_params
    params.require(:todo_item).permit(:name, :completed, :due_date)
  end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  include Dry::Monads[:result]

  before_action :set_todo_list, only: %i[show edit update destroy]

  def index
    @todo_lists = TodoList.all
  end

  def show
    @todo_items = case params[:filter]
    when "completed"
                    @todo_list.items.completed
    when "pending"
                    @todo_list.items.pending
    else
                    @todo_list.items
    end

    if turbo_frame_request?
      render @todo_items
    else
      render :show
    end
  end

  def new
    @todo_list = TodoList.new

    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end

  def edit
    render partial: "edit", locals: { todo_list: @todo_list }
  end

  def create
    @todo_list = TodoList.new(todo_list_params)

    result = TodoLists::CreateTodoListService.new(todo_list_params).call

    case result
    when Success
      @todo_list = result.success

      respond_to do |format|
        format.turbo_stream
      end
    when Failure
      respond_to do |format|
        format.turbo_stream { render turbo_stream: turbo_stream.update("new_todo_list", partial: "todo_lists/form", locals: { todo_list: @todo_list, errors: result.failure }), status: :unprocessable_entity }
      end
    end
  end

  def update
    result = TodoLists::UpdateTodoListService.new(@todo_list, todo_list_params).call

    case result
    when Success
      respond_to do |format|
        format.turbo_stream
      end
    when Failure
      render :edit, status: :unprocessable_entity, locals: { errors: result.failure }
    end
  end

  def destroy
    result = TodoLists::DestroyTodoListService.new(@todo_list).call

    case result
    when Success
      respond_to do |format|
        format.html { redirect_to todo_lists_path, status: :see_other, notice: "Todo list was successfully destroyed." }
        format.json { head :no_content }
      end
    when Failure
      respond_to do |format|
        format.turbo_stream { render turbo_stream: turbo_stream.replace("todo_list_#{@todo_list.id}", partial: "todo_lists/todo_list", locals: { todo_list: @todo_list, errors: result.failure }), status: :unprocessable_entity }
        format.html { render :index, status: :unprocessable_entity, locals: { errors: result.failure } }
      end
    end
  end

  private

    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    def todo_list_params
      params.require(:todo_list).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>TiTodo</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="A production ready example Rails app that's using Docker and Docker Compose.">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

    <%# Generated with: https://realfavicongenerator.net/ %>
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#61b9d2">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
  </head>

  <body class="flex flex-col h-screen justify-between">
    <main class="bg-gray-200 min-h-screen flex items-center justify-center py-4">
      <div class="mx-auto w-3/5">
          <div class="text-center mb-8">
            <h1 class="text-6xl font-bold text-gray-800 mb-2">TiTodo</h1>

            <% if [root_path, todo_lists_path].include?(request.path) %>
              <p class="text-xl text-gray-600">What needs to be done?</p>
            <% end %>
          </div>
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/pages/home.html.erb
<div class="flex justify-center pt-24 pb-12 px-2 sm:px-0">
  <%= image_tag "ruby-on-rails.png", size: "480x188", alt: "Rails logo" %>
</div>

<p class="text-center text-lg">
 🐳 Learn the Docker fundamentals at:
  <strong>
    <a class="border-b border-gray-900 mb-1" href="https://diveintodocker.com?ref=docker-rails-example">https://diveintodocker.com</a>
  </strong>
</p>

app/views/todo_items/_edit.html.erb
<%= turbo_frame_tag dom_id(todo_item), data: { controller: "autofocus" } do %>
  <div class="flex items-center justify-between p-4 <%= todo_item.completed ? "bg-green-100" : "bg-gray-100" %> shadow-md rounded-lg mb-4">
    <%= form_with model: todo_item, url: todo_list_todo_item_path(todo_item.todo_list, todo_item), method: :patch, data: { turbo_frame: dom_id(todo_item) }, class: "flex-1 flex items-center space-x-2" do |f| %>
      <%= f.text_field :name, autofocus: true, class: "rounded bg-[rgba(255,255,255,0.5)] p-2 w-full text-lg font-semibold text-gray-900 cursor-text focus:outline-none focus:ring-0" %>
      
      <%= f.submit "💾", class: "text-blue-500 hover:text-blue-700 cursor-pointer" %>
    <% end %>
  </div>
<% end %>

app/views/todo_items/_form.html.erb
<% errors ||= [] %>

<%= form_with(model: [todo_item.todo_list, todo_item]) do |form| %>
  <% if errors.any? %>
    <div class="bg-red-100 text-red-700 p-4 rounded-md mb-4">
      <h2 class="font-semibold"><%= pluralize(errors.count, "error") %> prohibited this todo item from being saved:</h2>
      <ul class="list-inside list-disc">
        <% errors.each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="flex items-center space-x-4">
    <div class="flex-1">
      <%= form.text_field :name, class: "mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500", placeholder: "What needs to be done?" %>
    </div>

    <div class="flex items-center justify-center">
      <%= form.submit "+", class: "inline-block w-10 h-10 bg-blue-500 text-white rounded-full shadow hover:bg-blue-600" %>
    </div>
  </div>
<% end %>

app/views/todo_items/_list.html.erb
<%= turbo_frame_tag "todo_items" do %>
  <% if todo_items.any? %>
    <% todo_items.order(created_at: :asc).each do |item| %>
      <%= render item %>
    <% end %>
  <% else %>
    <p class="text-gray-500 text-center">No items found.</p>
  <% end %>
<% end %>

app/views/todo_items/_todo_item.html.erb
<%= turbo_frame_tag dom_id(todo_item) do %>
  <div class="group flex items-center justify-between p-4 <%= todo_item.completed ? "bg-green-100" : "bg-gray-100" %> shadow-md rounded-lg mb-4">
    <div class="flex-1 flex items-center space-x-2">
      <h2 class="text-lg font-semibold text-gray-900">
        <%= todo_item.name %>
      </h2>

      <%= link_to "✏️", edit_todo_list_todo_item_path(todo_item.todo_list, todo_item), data: { turbo_frame: dom_id(todo_item) }, class: "hidden group-hover:inline text-gray-500 hover:text-gray-700 cursor-pointer" %>
    </div>

    <div class="flex items-center space-x-4">
      <%= check_box_tag "completed", true, todo_item.completed, class: "w-5 h-5 rounded-full text-green-300 cursor-pointer", id: dom_id(todo_item, "checkbox"), data: { controller: "checkbox", action: "change->checkbox#toggle", checkbox_url_value: todo_list_todo_item_path(todo_item.todo_list, todo_item) } %>

      <%= button_to "✖", todo_list_todo_item_path(todo_item.todo_list, todo_item), method: :delete, class: "text-red-500 hover:text-red-700 cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
    </div>
  </div>
<% end %>

app/views/todo_items/_todo_items.html.erb
<%= turbo_frame_tag "todo_items" do %>
  <% if todo_items.any? %>
    <% todo_items.order(created_at: :asc).each do |item| %>
      <%= render item %>
    <% end %>
  <% else %>
    <p class="text-gray-500 text-center">No items found.</p>
  <% end %>
<% end %>

app/views/todo_items/create.turbo_stream.erb
<%= turbo_stream.append("todo_items", partial: "todo_item", locals: { todo_item: @todo_item }) %>

<%= turbo_stream.update("new_todo_item", partial: "form", locals: { todo_item: @todo_list.items.new }) %>

<%= turbo_stream.replace("items_counter", partial: "todo_lists/counter", locals: { todo_list: @todo_list.reload }) %>

app/views/todo_items/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@todo_item) %>

<%= turbo_stream.replace("items_counter", partial: "todo_lists/counter", locals: { todo_list: @todo_list.reload }) %>

app/views/todo_items/new.html.erb
<%= turbo_frame_tag :new_todo_item do %>
  <%= render "form", todo_item: @todo_item %>
<% end %>

app/views/todo_items/show.html.erb
<div>
  <%= link_to "Edit this todo item", edit_todo_list_todo_item_path(@todo_item.todo_list, @todo_item) %> |
  <%= link_to "Back to todo items", todo_list_todo_items_path(@todo_item.todo_list) %>

  <%= button_to "Destroy this todo item", todo_list_todo_item_path(@todo_item.todo_list, @todo_item), method: :delete %>
</div>

app/views/todo_items/update.turbo_stream.erb
<%= turbo_stream.replace(dom_id(@todo_item), partial: "todo_items/todo_item", locals: { todo_item: @todo_item.reload }) %>

<%= turbo_stream.replace("items_counter", partial: "todo_lists/counter", locals: { todo_list: @todo_list.reload }) %>

app/views/todo_lists/_counter.html.erb
<div id="items_counter" class="flex items-center space-x-2 ml-auto">
  <span><%= todo_list.items.completed.count %></span>
  <span> / </span>
  <span><%= todo_list.items.count %></span>
</div>

app/views/todo_lists/_edit.html.erb
<%= turbo_frame_tag dom_id(todo_list, :name) do %>
  <div class="flex items-center space-x-2">
    <%= form_with model: todo_list, url: todo_list_path(todo_list), method: :patch, data: { turbo_frame: dom_id(todo_list, :name) }, class: "flex-1 flex items-center space-x-2" do |f| %>
      <%= f.text_field :name, autofocus: true, class: "border p-2 rounded w-full text-2xl font-bold" %>
      
      <%= f.submit "💾", class: "text-blue-500 hover:text-blue-700 cursor-pointer" %>
    <% end %>
  </div>
<% end %>

app/views/todo_lists/_form.html.erb
<% errors ||= [] %>

<%= form_with(model: todo_list) do |form| %>
  <% if errors.any? %>
    <div class="bg-red-100 text-red-700 p-4 rounded-md my-4">
      <h2 class="font-semibold"><%= pluralize(errors.count, "error") %> prohibited this todo list from being saved:</h2>
      <ul class="list-inside list-disc">
        <% errors.each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="flex items-center space-x-4">
    <div class="flex-1">
      <%= form.text_field :name, class: "mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500", placeholder: "Enter new todo list name" %>
    </div>

    <div class="flex items-center justify-center">
      <%= form.submit "+", class: "inline-block w-10 h-10 bg-blue-500 text-white rounded-full shadow hover:bg-blue-600" %>
    </div>
  </div>
<% end %>

app/views/todo_lists/_title.html.erb
<%= turbo_frame_tag dom_id(todo_list, :name) do %>
  <div class="group flex items-center space-x-2">
    <h1 class="text-2xl font-bold text-gray-900">
      <%= todo_list.name %>
    </h1>

    <%= link_to "✏️", edit_todo_list_path(todo_list), data: { turbo_frame: dom_id(todo_list, :name) }, class: "hidden group-hover:inline text-gray-500 hover:text-gray-700 cursor-pointer" %>
  </div>
<% end %>

app/views/todo_lists/_todo_list.html.erb
<%= link_to todo_list, class: "block" do %>
  <div class="max-w-4xl mx-auto p-6 bg-white rounded-lg shadow-md hover:bg-gray-50 cursor-pointer">
    <div class="flex items-center justify-between w-full">
      <h1 class="text-2xl font-bold text-gray-900">
        <%= todo_list.name %>
      </h1>

      <%= render "counter", todo_list: todo_list %> 
    </div>
  </div>
<% end %>

app/views/todo_lists/_todo_lists.html.erb
<div class="">
  <div id="todo_lists" class="space-y-4">
    <% todo_lists.each do |todo_list| %>
      <%= render "todo_lists/todo_list", todo_list: todo_list %> 
    <% end %>
  </div>
</div>

app/views/todo_lists/create.turbo_stream.erb
<% if TodoList.count == 1 %>
  <%= turbo_stream.replace "todo_lists_empty", partial: "todo_lists/todo_lists", locals: { todo_lists: TodoList.all } %>
<% else %>
  <%= turbo_stream.append "todo_lists", partial: "todo_lists/todo_list", locals: { todo_list: @todo_list } %>

  <%= turbo_stream.update "new_todo_list", partial: "todo_lists/form", locals: { todo_list: TodoList.new } %>
<% end %>

app/views/todo_lists/index.html.erb
<% if @todo_lists.empty? %>
  <div id="todo_lists_empty" class="text-center py-8">
    <h2 class="text-3xl font-semibold text-gray-700 mb-4">You have no todo lists yet 🫤</h2>
    <p class="text-lg text-gray-500 mb-6">Start by creating your first Todo List and organize what needs to be done!</p>
  </div>
<% else %>
    <%= render partial: "todo_lists/todo_lists", locals: { todo_lists: @todo_lists } %>
<% end %>

  <div class="max-w-4xl my-4 mx-auto p-6 bg-white rounded-lg shadow-md">
    <%= turbo_frame_tag "new_todo_list" do %>
      <%= render "form", todo_list: TodoList.new %> 
    <% end %>
  </div>

<%= turbo_stream_from "todo_lists" %>

app/views/todo_lists/new.html.erb
<%= turbo_frame_tag :new_todo_list do %>
  <%= render "form", todo_list: @todo_list %>
<% end %>

app/views/todo_lists/show.html.erb
<div class="max-w-3xl mx-auto justify-between my-4">
  <%= link_to "< View all todo lists", todo_lists_path, class: "text-gray-700" %>
</div>

<div class="max-w-3xl mx-auto p-6 bg-white rounded-lg shadow-md">
  <div class="flex items-center justify-between w-full">
    <%= render "title", todo_list: @todo_list %>

    <%= button_to @todo_list, method: :delete, class: "text-red-500 hover:text-red-700 cursor-pointer", data: { turbo_confirm: "Are you sure?" } do %>
      <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 inline" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
        <polyline points="3 6 5 6 21 6"></polyline>
        <path d="M19 6l-2 14a2 2 0 0 1-2 2H9a2 2 0 0 1-2-2L5 6"></path>
        <path d="M10 11v6"></path>
        <path d="M14 11v6"></path>
        <path d="M4 6h16"></path>
        <path d="M9 6V4a2 2 0 0 1 2-2h2a2 2 0 0 1 2 2v2"></path>
      </svg>
    <% end %>
  </div>

  <div id="todo_items_filter" data-controller="filter" class="flex w-full my-4">
    <div class="inline-flex w-full rounded-lg border border-gray-300 flex-col sm:flex-row">
      <%= link_to "All", 
        todo_list_path(@todo_list), 
        data: { turbo_frame: "todo_items", action: "filter#update", filter_target: "button" }, 
        class: "w-full sm:w-1/3 px-4 py-2 text-center border-b sm:border-b-0 sm:border-r border-gray-300" %> 

      <%= link_to "Completed", 
        todo_list_path(@todo_list, filter: "completed"), 
        data: { turbo_frame: "todo_items", action: "filter#update", filter_target: "button" }, 
        class: "w-full sm:w-1/3 px-4 py-2 text-center border-b sm:border-b-0 sm:border-r border-gray-300" %> 

      <%= link_to "Pending", 
        todo_list_path(@todo_list, filter: "pending"), 
        data: { turbo_frame: "todo_items", action: "filter#update", filter_target: "button" }, 
        class: "w-full sm:w-1/3 px-4 py-2 text-center border-b sm:border-b-0" %> 
    </div>
  </div>


  <div class="flex ml-auto mb-2">
    <%= render "counter", todo_list: @todo_list %>
  </div>


  <%= turbo_frame_tag "todo_items" do %>
    <%= render @todo_items %>
  <% end %>

  <%= turbo_frame_tag :new_todo_item, src: new_todo_list_todo_item_path(@todo_list) %>
</div>

app/views/todo_lists/update.turbo_stream.erb
<%# render partial: "todo_lists/title", locals: { todo_list: @todo_list } %>

<%= turbo_stream.replace(dom_id(@todo_list, :name), partial: "todo_lists/title", locals: { todo_list: @todo_list.reload }) %>